### ISSUE TITLE
Division by zero in successrate.sh

### ISSUE THREAD

**Issue by uniconstructor** [gsxryan/storj_telegraf_mon#20]
If your node have 0 repair requests processed, telegraf fails to parse stats:

Here is my telegraf stats when running test (fresh install):
```sh
docker exec -i -t telegraf /bin/bash
root@2b893255a418:/# telegraf --debug --config /etc/telegraf/telegraf.conf --input-filter exec --test
2019-08-07T03:04:19Z I! Starting Telegraf 1.11.3
2019-08-07T03:04:21Z E! [inputs.exec]: Error in plugin: metric parse error: expected field at 3:77: "StorJHealth,NodeId=12bqvr GETRepairFail=0,GETRepairSuccess=0,GETRepairRatio=nan,PUTRepairFailed=0,PUTRepairSuccess=0,PUTRepairRatio=0.000 1565147061042414707"
> StorJToken,WalletAddress="0x0000000000000000",host=2b893255a418,stat=tokens BalanceEUR=1.01111,BalanceSTORJ=1.0111,BalanceUSD=1.0111 1565147063000000000
> StorJToken,host=2b893255a418,stat=prices STORJPriceEUR=0.1395,STORJPriceUSD=0.1565 1565147063000000000
> StorJHealth,host=2b893255a418,path="/storage/storj" directory_size_kilobytes=301643780 1565147063000000000
``` 
(balances and ETH address are replaced by dummy values)

I don't know what actually means "metric parse error: expected field", but I suspect that problem is caused by **GETRepairRatio=nan**.

Nan here is caused with division by zero in line 88: https://github.com/gsxryan/storj_telegraf_mon/blob/master/successrate.sh#L88

(Actually you don't have a "division-by-zero" check in all ratio-based calculations in successrate.sh).

**Comment by uniconstructor** [comment]
UPD: 
1) cannot clear the old values from telegraf DB
2) Maybe the problem is not related to "divide-by-zero" at all: I looked at the logs more carefully and noticed that any "Ratio"-based value is a float. Script prints those floats via printf with 3 digits precision. And here comes a very important detail: 

> printf output format may depend on current locale

That means, that in some systems with locale other that EN you can see result of a printf like this:

./successrate.sh 
StorJHealth,NodeId=12bqvr FailedCrit=0,FailedWarn=0,Success=261,**Ratio=100,000**,Deleted=0 1565148928486856016

(example output from my server, default system locale: RU)

**Comment by gsxryan** [comment]
I think you have identified 3 issues here

It appears you are using the docker-compose, and are inside the telegraf container.  I have summarized current issues with the docker-compose in https://github.com/gsxryan/storj_telegraf_mon/projects/1

1) 2019-08-07T03:04:21Z E! [inputs.exec]: Error in plugin: metric parse error: expected field at 3:77: 
You can replicate this by running ./etc/telegraf/successrates.sh inside the telegraf container.  I think the permissions to the host docker instance is blocked.  This can be fixed by using a logfile instead of docker commands, or we need to figure out how to give the telegraf container, access to the host docker group.

2) nan values - while invalid when sent to influxdb, it shouldn't cause a critical error.

3) system locale breaking proper influxDB formatting.  A comma in the ratio value will terminate the value early, and create invalid syntax when importing to influx.  Recommend changing locale, or figuring out how to handle or force a specific locale in successrates.sh

**Comment by gsxryan** [comment]
Summarized Issues discovered in Project Tab for Docker-Compose.
